env:
  PROJECT_ID: coen6313

name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest


  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Cloud Instance
        uses: appleboy/ssh-action@v1.0.3
        with:
           - name: Google Cloud Auth
             uses: 'google-github-actions/auth@v2'
             with:
              credentials_json: '${{ secrets.GCP_SA_KEY }}'
              project_id: ${{ env.PROJECT_ID }}
          
          script: |
            cd /path/to/your/app
            git pull origin main
            docker-compose down
            docker-compose up -d --build
